auto build alpine

diff --git a/.github/workflows/auto-build.yml b/.github/workflows/auto-build.yml
--- a/.github/workflows/auto-build.yml
+++ b/.github/workflows/auto-build.yml
@@ -35,10 +35,44 @@ jobs:
           body: Auto build from ${{ github.sha }} (master)
           draft: false
           prerelease: true
+
+  build-musl:
+    name: Build musl version
+    runs-on: [self-hosted, linux, golang]
+    needs: prerelease
+    env:
+      http_proxy: http://proxy-server.:3271
+      https_proxy: http://proxy-server.:3271
+      GOPROXY: https://proxy.golang.org
+      GOCACHE: /data/Cache/golang
+      GO111MODULE: auto
+      GOPATH: /data/DevelopmentRoot/GoLang
+    steps:
+      - name: checkout
+        uses: actions/checkout@v2
+
+      - name: Build
+        id: build
+        run: |
+          pwsh ./scripts/build.ps1 musl
+
+      - name: Upload Release Asset
+        id: upload-release-asset
+        uses: actions/upload-release-asset@v1.0.1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ needs.prerelease.outputs.upload_url }}
+          asset_path: dist/${{ steps.build.outputs.artifact }}
+          asset_name: ${{ steps.build.outputs.artifact }}
+          asset_content_type: application/octet-stream
+
   build:
     name: Build
     runs-on: ${{ matrix.os }}
+    needs: prerelease
     strategy:
+      fail-fast: false
       matrix:
         os: [windows-latest, ubuntu-latest]
         project:
@@ -48,7 +82,6 @@ jobs:
         exclude:
           - os: windows-latest
             project: server
-    needs: prerelease
     steps:
       - name: checkout
         uses: actions/checkout@v2
@@ -73,14 +106,20 @@ jobs:
         run: |
           go mod download
           cd ..
-          go get -v -u github.com/GongT/go-generate-struct-interface/cmd/go-generate-struct-interface github.com/golang/protobuf/protoc-gen-go
+          go get -u github.com/GongT/go-generate-struct-interface/cmd/go-generate-struct-interface github.com/golang/protobuf/protoc-gen-go
 
       - name: Build
         id: build
+        shell: pwsh
         run: |
           pwsh ./scripts/build.ps1 ${{ matrix.project }}
-          echo "command result: $?"
-          sleep 5
+          if ($?) {
+            echo "build complete!"
+          }else{
+            echo "build failed!"
+            sleep 5
+            exit 1
+          }
 
       - name: Upload Release Asset
         id: upload-release-asset
